using System;
using System.Collections.Generic;
using System.Linq;
using JourneyPlanner_ClassLibrary.Classes;
using Microsoft.VisualBasic.FileIO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace JourneyPlanner_Tests.UnitTests.Classes
{
    [TestClass]
    public class AirportUnitTests
    {
        [TestMethod]
        public void AirportsHaveEqualHashCode()
        {
            Assert.IsTrue(
                new Airport("a", "a", "Bulgaria", "a", "a").GetHashCode() ==
                new Airport("a", "a", "Bulgaria", "a", "a").GetHashCode()
            );
        }

        [TestMethod]
        public void AirportsAreEqual()
        {
            Assert.IsTrue(
                new Airport("a", "a", "Bulgaria", "a", "a").Equals(new Airport("a", "a", "Bulgaria", "a", "a"))
            );
        }

        [TestMethod]
        public void AirportsAreNotEqual()
        {
            Assert.IsFalse(new Airport("a", "a", "Bulgaria", "a", "a").Equals(1));
        }

        // [TestMethod]
        // public void asd()
        // {
        //     var data = new List<string>
        //     {
        //         "Wings-t",
        //         "7th Heaven-f",
        //         "The Racket-f",
        //         "The Broadway Melody-t",
        //         "Alibi-f",
        //         "Hollywood Revue-f",
        //         "In Old Arizona-f",
        //         "The Patriot-f",
        //         "All Quiet on the Western Front-t",
        //         "The Big House-f",
        //         "Disraeli-f",
        //         "The Divorcee-f",
        //         "The Love Parade-f",
        //         "Cimarron-t",
        //         "East Lynne-f",
        //         "The Front Page-f",
        //         "Skippy-f",
        //         "Trader Horn-f",
        //         "Grand Hotel-t",
        //         "Arrowsmith-f",
        //         "Bad Girl-f",
        //         "The Champ-f",
        //         "Five Star Final-f",
        //         "One Hour with You-f",
        //         "Shanghai Express-f",
        //         "The Smiling Lieutenant-f",
        //         "Cavalcade-t",
        //         "42nd Street-f",
        //         "A Farewell to Arms-f",
        //         "I Am a Fugitive from a Chain Gang-f",
        //         "Lady for a Day-f",
        //         "Little Women-f",
        //         "The Private Life of Henry VIII-f",
        //         "She Done Him Wrong-f",
        //         "Smilin' Through-f",
        //         "State Fair-f",
        //         "It Happened One Night-t",
        //         "The Barretts of Wimpole Street-f",
        //         "Cleopatra-f",
        //         "Flirtation Walk-f",
        //         "The Gay Divorcee-f",
        //         "Here Comes the Navy-f",
        //         "The House of Rothschild-f",
        //         "Imitation of Life-f",
        //         "One Night of Love-f",
        //         "The Thin Man-f",
        //         "Viva Villa!-f",
        //         "The White Parade-f",
        //         "Mutiny on the Bounty-t",
        //         "Alice Adams-f",
        //         "Broadway Melody of 1936-f",
        //         "Captain Blood-f",
        //         "David Copperfield-f",
        //         "The Informer-f",
        //         "The Lives of a Bengal Lancer-f",
        //         "A Midsummer Night's Dream-f",
        //         "Les Misérables-f",
        //         "Naughty Marietta-f",
        //         "Ruggles of Red Gap-f",
        //         "Top Hat-f",
        //         "The Great Ziegfeld-t",
        //         "Anthony Adverse-f",
        //         "Dodsworth-f",
        //         "Libeled Lady-f",
        //         "Mr. Deeds Goes to Town-f",
        //         "Romeo and Juliet-f",
        //         "San Francisco-f",
        //         "The Story of Louis Pasteur-f",
        //         "A Tale of Two Cities-f",
        //         "Three Smart Girls-f",
        //         "The Life of Emile Zola-t",
        //         "The Awful Truth-f",
        //         "Captains Courageous-f",
        //         "Dead End-f",
        //         "The Good Earth-f",
        //         "In Old Chicago-f",
        //         "Lost Horizon-f",
        //         "One Hundred Men and a Girl-f",
        //         "Stage Door-f",
        //         "A Star Is Born-f",
        //         "You Can't Take It with You-t",
        //         "The Adventures of Robin Hood-f",
        //         "Alexander's Ragtime Band-f",
        //         "Boys Town-f",
        //         "The Citadel-f",
        //         "Four Daughters-f",
        //         "Grand Illusion-f",
        //         "Jezebel-f",
        //         "Pygmalion-f",
        //         "Test Pilot-f",
        //         "Gone with the Wind-t",
        //         "Dark Victory-f",
        //         "Goodbye, Mr. Chips-f",
        //         "Love Affair-f",
        //         "Mr. Smith Goes to Washington-f",
        //         "Ninotchka-f",
        //         "Of Mice and Men-f",
        //         "Stagecoach-f",
        //         "The Wizard of Oz-f",
        //         "Wuthering Heights-f",
        //         "Rebecca-t",
        //         "All This, and Heaven Too-f",
        //         "Foreign Correspondent-f",
        //         "The Grapes of Wrath-f",
        //         "The Great Dictator-f",
        //         "Kitty Foyle-f",
        //         "The Letter-f",
        //         "The Long Voyage Home-f",
        //         "Our Town-f",
        //         "The Philadelphia Story-f",
        //         "How Green Was My Valley-t",
        //         "Blossoms in the Dust-f",
        //         "Citizen Kane-f",
        //         "Here Comes Mr. Jordan-f",
        //         "Hold Back the Dawn-f",
        //         "The Little Foxes-f",
        //         "The Maltese Falcon-f",
        //         "One Foot in Heaven-f",
        //         "Sergeant York-f",
        //         "Suspicion-f",
        //         "Mrs. Miniver-t",
        //         "49th Parallel[43]-f",
        //         "Kings Row-f",
        //         "The Magnificent Ambersons-f",
        //         "The Pied Piper-f",
        //         "The Pride of the Yankees-f",
        //         "Random Harvest-f",
        //         "The Talk of the Town-f",
        //         "Wake Island-f",
        //         "Yankee Doodle Dandy-f",
        //         "Casablanca-t",
        //         "For Whom the Bell Tolls-f",
        //         "Heaven Can Wait-f",
        //         "The Human Comedy-f",
        //         "In Which We Serve-f",
        //         "Madame Curie-f",
        //         "The More the Merrier-f",
        //         "The Ox-Bow Incident-f",
        //         "The Song of Bernadette-f",
        //         "Watch on the Rhine-f",
        //         "Going My Way-t",
        //         "Double Indemnity-f",
        //         "Gaslight-f",
        //         "Since You Went Away-f",
        //         "Wilson-f",
        //         "The Lost Weekend-t",
        //         "Anchors Aweigh-f",
        //         "The Bells of St. Mary's-f",
        //         "Mildred Pierce-f",
        //         "Spellbound-f",
        //         "The Best Years of Our Lives-t",
        //         "Henry V-f",
        //         "It's a Wonderful Life-f",
        //         "The Razor's Edge-f",
        //         "The Yearling-f",
        //         "Gentleman's Agreement-t",
        //         "The Bishop's Wife-f",
        //         "Crossfire-f",
        //         "Great Expectations-f",
        //         "Miracle on 34th Street-f",
        //         "Hamlet-t",
        //         "Johnny Belinda-f",
        //         "The Red Shoes-f",
        //         "The Snake Pit-f",
        //         "The Treasure of the Sierra Madre-f",
        //         "All the King's Men-t",
        //         "Battleground-f",
        //         "The Heiress-f",
        //         "A Letter to Three Wives-f",
        //         "Twelve O'Clock High-f",
        //         "All About Eve-t",
        //         "Born Yesterday-f",
        //         "Father of the Bride-f",
        //         "King Solomon's Mines-f",
        //         "Sunset Boulevard-f",
        //         "An American in Paris-t",
        //         "Decision Before Dawn-f",
        //         "A Place in the Sun-f",
        //         "Quo Vadis-f",
        //         "A Streetcar Named Desire-f",
        //         "The Greatest Show on Earth-t",
        //         "High Noon-f",
        //         "Ivanhoe-f",
        //         "Moulin Rouge-f",
        //         "The Quiet Man-f",
        //         "From Here to Eternity-t",
        //         "Julius Caesar-f",
        //         "The Robe-f",
        //         "Roman Holiday-f",
        //         "Shane-f",
        //         "On the Waterfront-t",
        //         "The Caine Mutiny-f",
        //         "The Country Girl-f",
        //         "Seven Brides for Seven Brothers-f",
        //         "Three Coins in the Fountain-f",
        //         "Marty-t",
        //         "Love Is a Many-Splendored Thing-f",
        //         "Mister Roberts-f",
        //         "Picnic-f",
        //         "The Rose Tattoo-f",
        //         "Around the World in 80 Days-t",
        //         "Friendly Persuasion-f",
        //         "Giant-f",
        //         "The King and I-f",
        //         "The Ten Commandments-f",
        //         "The Bridge on the River Kwai-t",
        //         "12 Angry Men-f",
        //         "Peyton Place-f",
        //         "Sayonara-f",
        //         "Witness for the Prosecution-f",
        //         "Gigi-t",
        //         "Auntie Mame-f",
        //         "Cat on a Hot Tin Roof-f",
        //         "The Defiant Ones-f",
        //         "Separate Tables-f",
        //         "Ben-Hur-t",
        //         "Anatomy of a Murder-f",
        //         "The Diary of Anne Frank-f",
        //         "The Nun's Story-f",
        //         "Room at the Top-f",
        //         "The Apartment-t",
        //         "The Alamo-f",
        //         "Elmer Gantry-f",
        //         "Sons and Lovers-f",
        //         "The Sundowners-f",
        //         "West Side Story-t",
        //         "Fanny-f",
        //         "The Guns of Navarone-f",
        //         "The Hustler-f",
        //         "Judgment at Nuremberg-f",
        //         "Lawrence of Arabia-t",
        //         "The Longest Day-f",
        //         "The Music Man-f",
        //         "Mutiny on the Bounty-f",
        //         "To Kill a Mockingbird-f",
        //         "Tom Jones-t",
        //         "America America-f",
        //         "Cleopatra-f",
        //         "How the West Was Won-f",
        //         "Lilies of the Field-f",
        //         "My Fair Lady-t",
        //         "Becket-f",
        //         "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb-f",
        //         "Mary Poppins-f",
        //         "Zorba the Greek-f",
        //         "The Sound of Music-t",
        //         "Darling-f",
        //         "Doctor Zhivago-f",
        //         "Ship of Fools-f",
        //         "A Thousand Clowns-f",
        //         "A Man for All Seasons-t",
        //         "Alfie-f",
        //         "The Russians Are Coming, the Russians Are Coming-f",
        //         "The Sand Pebbles-f",
        //         "Who's Afraid of Virginia Woolf?-f",
        //         "In the Heat of the Night-t",
        //         "Bonnie and Clyde-f",
        //         "Doctor Dolittle-f",
        //         "The Graduate-f",
        //         "Guess Who's Coming to Dinner-f",
        //         "Oliver!-t",
        //         "Funny Girl-f",
        //         "The Lion in Winter-f",
        //         "Rachel, Rachel-f",
        //         "Romeo and Juliet-f",
        //         "Midnight Cowboy-t",
        //         "Anne of the Thousand Days-f",
        //         "Butch Cassidy and the Sundance Kid-f",
        //         "Hello, Dolly!-f",
        //         "Z-f",
        //         "Patton-t",
        //         "Airport-f",
        //         "Five Easy Pieces-f",
        //         "Love Story-f",
        //         "M*A*S*H-f",
        //         "The French Connection-t",
        //         "A Clockwork Orange-f",
        //         "Fiddler on the Roof-f",
        //         "The Last Picture Show-f",
        //         "Nicholas and Alexandra-f",
        //         "The Godfather-t",
        //         "Cabaret-f",
        //         "Deliverance-f",
        //         "The Emigrants-f",
        //         "Sounder-f",
        //         "The Sting-t",
        //         "American Graffiti-f",
        //         "Cries and Whispers-f",
        //         "The Exorcist-f",
        //         "A Touch of Class-f",
        //         "The Godfather Part II-t",
        //         "Chinatown-f",
        //         "The Conversation-f",
        //         "Lenny-f",
        //         "The Towering Inferno-f",
        //         "One Flew Over the Cuckoo's Nest-t",
        //         "Barry Lyndon-f",
        //         "Dog Day Afternoon-f",
        //         "Jaws-f",
        //         "Nashville-f",
        //         "Rocky-t",
        //         "All the President's Men-f",
        //         "Bound for Glory-f",
        //         "Network-f",
        //         "Taxi Driver-f",
        //         "Annie Hall-t",
        //         "The Goodbye Girl-f",
        //         "Julia-f",
        //         "Star Wars-f",
        //         "The Turning Point-f",
        //         "The Deer Hunter-t",
        //         "Coming Home-f",
        //         "Heaven Can Wait-f",
        //         "Midnight Express-f",
        //         "An Unmarried Woman-f",
        //         "Kramer vs. Kramer-t",
        //         "All That Jazz-f",
        //         "Apocalypse Now-f",
        //         "Breaking Away-f",
        //         "Norma Rae-f",
        //         "Ordinary People-t",
        //         "Coal Miner's Daughter-f",
        //         "The Elephant Man-f",
        //         "Raging Bull-f",
        //         "Tess-f",
        //         "Chariots of Fire-t",
        //         "Atlantic City-f",
        //         "On Golden Pond-f",
        //         "Raiders of the Lost Ark-f",
        //         "Reds-f",
        //         "Gandhi-t",
        //         "E.T. the Extra-Terrestrial-f",
        //         "Missing-f",
        //         "Tootsie-f",
        //         "The Verdict-f",
        //         "Terms of Endearment-t",
        //         "The Big Chill-f",
        //         "The Dresser-f",
        //         "The Right Stuff-f",
        //         "Tender Mercies-f",
        //         "Amadeus-t",
        //         "The Killing Fields-f",
        //         "A Passage to India-f",
        //         "Places in the Heart-f",
        //         "A Soldier's Story-f",
        //         "Out of Africa-t",
        //         "The Color Purple-f",
        //         "Kiss of the Spider Woman-f",
        //         "Prizzi's Honor-f",
        //         "Witness-f",
        //         "Platoon-t",
        //         "Children of a Lesser God-f",
        //         "Hannah and Her Sisters-f",
        //         "The Mission-f",
        //         "A Room with a View-f",
        //         "The Last Emperor-t",
        //         "Broadcast News-f",
        //         "Fatal Attraction-f",
        //         "Hope and Glory-f",
        //         "Moonstruck-f",
        //         "Rain Man-t",
        //         "The Accidental Tourist-f",
        //         "Dangerous Liaisons-f",
        //         "Mississippi Burning-f",
        //         "Working Girl-f",
        //         "Driving Miss Daisy-t",
        //         "Born on the Fourth of July-f",
        //         "Dead Poets Society-f",
        //         "Field of Dreams-f",
        //         "My Left Foot-f",
        //         "Dances with Wolves-t",
        //         "Awakenings-f",
        //         "Ghost-f",
        //         "The Godfather Part III-f",
        //         "Goodfellas-f",
        //         "The Silence of the Lambs-t",
        //         "Beauty and the Beast-f",
        //         "Bugsy-f",
        //         "JFK-f",
        //         "The Prince of Tides-f",
        //         "Unforgiven-t",
        //         "The Crying Game-f",
        //         "A Few Good Men-f",
        //         "Howards End-f",
        //         "Scent of a Woman-f",
        //         "Schindler's List-t",
        //         "The Fugitive-f",
        //         "In the Name of the Father-f",
        //         "The Piano-f",
        //         "The Remains of the Day-f",
        //         "Forrest Gump-t",
        //         "Four Weddings and a Funeral-f",
        //         "Pulp Fiction-f",
        //         "Quiz Show-f",
        //         "The Shawshank Redemption-f",
        //         "Braveheart-t",
        //         "Apollo 13-f",
        //         "Babe-f",
        //         "The Postman (Il Postino)-f",
        //         "Sense and Sensibility-f",
        //         "The English Patient-t",
        //         "Fargo-f",
        //         "Jerry Maguire-f",
        //         "Secrets & Lies-f",
        //         "Shine-f",
        //         "Titanic-t",
        //         "As Good as It Gets-f",
        //         "The Full Monty-f",
        //         "Good Will Hunting-f",
        //         "L.A. Confidential-f",
        //         "Shakespeare in Love-t",
        //         "Elizabeth-f",
        //         "Life Is Beautiful-f",
        //         "Saving Private Ryan-f",
        //         "The Thin Red Line-f",
        //         "American Beauty-t",
        //         "The Cider House Rules-f",
        //         "The Green Mile-f",
        //         "The Insider-f",
        //         "The Sixth Sense-f",
        //         "Gladiator-t",
        //         "Chocolat-f",
        //         "Crouching Tiger, Hidden Dragon-f",
        //         "Erin Brockovich-f",
        //         "Traffic-f",
        //         "A Beautiful Mind-t",
        //         "Gosford Park-f",
        //         "In the Bedroom-f",
        //         "The Lord of the Rings: The Fellowship of the Ring-f",
        //         "Moulin Rouge!-f",
        //         "Chicago-t",
        //         "Gangs of New York-f",
        //         "The Hours-f",
        //         "The Lord of the Rings: The Two Towers-f",
        //         "The Pianist-f",
        //         "The Lord of the Rings: The Return of the King-t",
        //         "Lost in Translation-f",
        //         "Master and Commander: The Far Side of the World-f",
        //         "Mystic River-f",
        //         "Seabiscuit-f",
        //         "Million Dollar Baby-t",
        //         "The Aviator-f",
        //         "Finding Neverland-f",
        //         "Ray-f",
        //         "Sideways-f",
        //         "Crash-t",
        //         "Brokeback Mountain-f",
        //         "Capote-f",
        //         "Good Night, and Good Luck-f",
        //         "Munich-f",
        //         "The Departed-t",
        //         "Babel-f",
        //         "Letters from Iwo Jima-f",
        //         "Little Miss Sunshine-f",
        //         "The Queen-f",
        //         "No Country for Old Men-t",
        //         "Atonement-f",
        //         "Juno-f",
        //         "Michael Clayton-f",
        //         "There Will Be Blood-f",
        //         "Slumdog Millionaire-t",
        //         "The Curious Case of Benjamin Button-f",
        //         "Frost/Nixon-f",
        //         "Milk-f",
        //         "The Reader-f",
        //         "The Hurt Locker-t",
        //         "Avatar-f",
        //         "The Blind Side-f",
        //         "District 9-f",
        //         "An Education-f",
        //         "Inglourious Basterds-f",
        //         "Precious: Based on the Novel 'Push' by Sapphire-f",
        //         "A Serious Man-f",
        //         "Up-f",
        //         "Up in the Air-f",
        //         "The King's Speech-t",
        //         "Black Swan-f",
        //         "The Fighter-f",
        //         "Inception-f",
        //         "The Kids Are All Right-f",
        //         "127 Hours-f",
        //         "The Social Network-f",
        //         "Toy Story 3-f",
        //         "True Grit-f",
        //         "Winter's Bone-f",
        //         "The Artist-t",
        //         "The Descendants-f",
        //         "Extremely Loud & Incredibly Close-f",
        //         "The Help-f",
        //         "Hugo-f",
        //         "Midnight in Paris-f",
        //         "Moneyball-f",
        //         "The Tree of Life-f",
        //         "War Horse-f",
        //         "Argo-t",
        //         "Amour-f",
        //         "Beasts of the Southern Wild-f",
        //         "Django Unchained-f",
        //         "Life of Pi-f",
        //         "Lincoln-f",
        //         "Les Misérables-f",
        //         "Silver Linings Playbook-f",
        //         "Zero Dark Thirty-f",
        //         "12 Years a Slave-t",
        //         "American Hustle-f",
        //         "Captain Phillips-f",
        //         "Dallas Buyers Club-f",
        //         "Gravity-f",
        //         "Her-f",
        //         "Nebraska-f",
        //         "Philomena-f",
        //         "The Wolf of Wall Street-f",
        //         "Birdman or (The Unexpected Virtue of Ignorance)-t",
        //         "American Sniper-f",
        //         "Boyhood-f",
        //         "The Grand Budapest Hotel-f",
        //         "The Imitation Game-f",
        //         "Selma-f",
        //         "The Theory of Everything-f",
        //         "Whiplash-f",
        //         "Spotlight-t",
        //         "The Big Short-f",
        //         "Bridge of Spies-f",
        //         "Brooklyn-f",
        //         "Mad Max: Fury Road-f",
        //         "The Martian-f",
        //         "The Revenant-f",
        //         "Room-f",
        //         "Moonlight-t",
        //         "Arrival-f",
        //         "Fences-f",
        //         "Hacksaw Ridge-f",
        //         "Hell or High Water-f",
        //         "Hidden Figures-f",
        //         "La La Land-f",
        //         "Lion-f",
        //         "Manchester by the Sea-f",
        //         "The Shape of Water-t",
        //         "Call Me by Your Name-f",
        //         "Darkest Hour-f",
        //         "Dunkirk-f",
        //         "Get Out-f",
        //         "Lady Bird-f",
        //         "Phantom Thread-f",
        //         "The Post-f",
        //         "Three Billboards Outside Ebbing, Missouri-f",
        //         "Green Book-t",
        //         "Black Panther-f",
        //         "BlacKkKlansman-f",
        //         "Bohemian Rhapsody-f",
        //         "The Favourite-f",
        //         "Roma-f",
        //         "A Star Is Born-f",
        //         "Vice-f",
        //         "Parasite-t",
        //         "Ford v Ferrari-f",
        //         "The Irishman-f",
        //         "Jojo Rabbit-f",
        //         "Joker-f",
        //         "Little Women-f",
        //         "Marriage Story-f",
        //         "1917-f",
        //         "Once Upon a Time in Hollywood-f",
        //         "Nomadland-t",
        //         "The Father-f",
        //         "Judas and the Black Messiah-f",
        //         "Mank-f",
        //         "Minari-f",
        //         "Promising Young Woman-f",
        //         "Sound of Metal-f",
        //         "The Trial of the Chicago 7-f",
        //         "CODA-t",
        //         "Belfast-f",
        //         "Don't Look Up-f",
        //         "Drive My Car-f",
        //         "Dune-f",
        //         "King Richard-f",
        //         "Licorice Pizza-f",
        //         "Nightmare Alley-f",
        //         "The Power of the Dog-f",
        //         "West Side Story-f",
        //         "Everything Everywhere All at Once-t",
        //         "All Quiet on the Western Front-f",
        //         "Avatar: The Way of Water-f",
        //         "The Banshees of Inisherin-f",
        //         "Elvis-f",
        //         "The Fabelmans-f",
        //         "Tár-f",
        //         "Top Gun: Maverick-f",
        //         "Triangle of Sadness-f",
        //         "Women Talking-f",
        //         "Oppenheimer-t",
        //         "American Fiction-f",
        //         "Anatomy of a Fall-f",
        //         "Barbie-f",
        //         "The Holdovers-f",
        //         "Killers of the Flower Moon-f",
        //         "Maestro-f",
        //         "Past Lives-f",
        //         "Poor Things-f",
        //         "The Zone of Interest-f",
        //     };
        //
        //     var namesWonMap = new Dictionary<string, bool>();
        //     foreach (var piece in data)
        //     {
        //         var name = piece[..^2];
        //         var won = piece[^1..] == "t";
        //         namesWonMap.TryAdd(name, won);
        //     }
        //
        //     var idRatingMap = new Dictionary<string, double>();
        //     var idVotesMap = new Dictionary<string, int>();
        //     var ratingsParser = new TextFieldParser(@"C:\Users\simme\Downloads\title.ratings.tsv\data.tsv");
        //     ratingsParser.Delimiters = new[] {"\t"};
        //
        //     var counter = -1;
        //     while (true)
        //     {
        //         counter++;
        //         string[] parts = ratingsParser.ReadFields();
        //         if (parts == null)
        //         {
        //             counter = -1;
        //             break;
        //         }
        //
        //         if (counter > 0)
        //         {
        //             idRatingMap.Add(parts[0], double.Parse(parts[1]));
        //             idVotesMap.Add(parts[0], int.Parse(parts[2]));
        //         }
        //     }
        //
        //     // var nameIdMap = new Dictionary<string, string>();
        //     var entries = new List<DTO>();
        //     var basicsParser = new TextFieldParser(@"C:\Users\simme\Downloads\title.basics.tsv\data.tsv");
        //     basicsParser.Delimiters = new[] {"\t"};
        //     while (true)
        //     {
        //         string[] parts;
        //         try
        //         {
        //             counter++;
        //             parts = basicsParser.ReadFields();
        //         }
        //         catch (MalformedLineException)
        //         {
        //             continue;
        //         }
        //
        //         if (parts == null)
        //         {
        //             counter = -1;
        //             break;
        //         }
        //
        //         if (counter > 0 && parts[1] == "movie")
        //         {
        //             var id = parts[0];
        //             var name = parts[2];
        //             int votes = idVotesMap.TryGetValue(id, out int v) ? v : 0;
        //             if (votes > 100000 && namesWonMap.ContainsKey(name))
        //             {
        //                 entries.Add(
        //                     new DTO
        //                     {
        //                         Name = name,
        //                         Rating = idRatingMap[id],
        //                         Votes = votes,
        //                         Year = int.Parse(parts[5]),
        //                         Won = namesWonMap[name],
        //                         Runtime = int.Parse(parts[7]),
        //                         Genres = parts[8],
        //                         Link = $"https://www.imdb.com/title/{id}/"
        //                     }
        //                 );
        //             }
        //         }
        //     }
        //
        //     entries = entries.OrderByDescending(e => e.Votes).ToList();
        //     var text = String.Join("\n", entries.Select(x => x.ToString()));
        //     var x = 1;
        // }

        public class DTO
        {
            public string Name { get; set; }
            public double Rating { get; set; }
            public int Votes { get; set; }
            public int Year { get; set; }
            public bool Won { get; set; }
            public int Runtime { get; set; }
            public string Genres { get; set; }
            public string Link { get; set; }

            public override string ToString()
            {
                return $"{Name}	{Rating}	{Votes}	{Year}	{Won}	{Runtime}	{Genres}	{Link}";
            }
        }
    }
}